travis:
  secure:
    BINSTAR_TOKEN: ljDTwfmrHvq0860MQUeoC/1yKHGAbcFY7RL0BWwx1ohL/pogNMtV9+FkoWy4k9Ip2KiBU/c8VF1K2Vb1xIgYvvdGIYoD7uPxuzjFuIsYc3mAMn2MCEX3AAFDMmvQPNPUaUtL5E/1c2Z9Gw8reOohyGb+UjULXcRwMoOv0pSEY8xSvRblRATPMI0ExLzqOWmGUu4TzOW913VAszrbekYde4I4PzCkDlWdBoeoWLqHrHTj1/IZa2vU4/My0YLnpsBNmyvk3m6tyOput8TLk+iT5f2/a/jglhOhg2vZsolzX4I2H4HMDpwQTr07TzgZfY7cjHw8PEI4jk/LZJHgco03Up4PiDSpR4r/QlqvSNFGTXxczaDLUj9XJjOqEYliKfDsGZ+LnUeZBSnMd40fcd04ScHZ6qaxUYgUtuwmzmnNuwuLOcYeXkJV7xnb7BIotIbpfBUb51pdxJHX4rvtsibZ1I/A1JOlC0JBnTIR3kcAPj14XAalBB9f6aUmtOVIwttQwCt6iAyN5fvll4QgipoguHgJ8xLm3r7iyBUUSjQpjI+oUWAkQaxYuNa5eFpcw09Jy598dx+jTacywktwNVvUa1sCKtfhSN/tao3VhQ8ZHGRH138D+ze/DiNtOvxhG9eVEEySgvPjRy5r/Ws0fhPX94WJqfkrcYWd9sO07yXroJI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
